### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [harryh/dayssinceacryptocurrencyexchangehaslostmorethan100million.github.io#4]
The site is inaccessible over IPv6.

**Comment by harryh** [comment]
Does Github Pages support IPv6? I'm not sure?

**Comment by tambry** [comment]
GitHub Pages is the only part of GitHub that has IPv6 support. That is, except if you're using a custom domain. Putting the site behind a Cloudflare proxy would allow both IPv6 and SSL support (note that the Cloudflare free tier provides both of these).

**Comment by harryh** [comment]
CloudFlare is a bit more trouble then I'm willing to take on for my little joke site. Alas, will have to remain IPv4 only for the time being.

**Comment by tambry** [comment]
I did some more research and found an easier, albeit unofficial method. That is, simply add 2A04:4E42:2E::403 as the AAAA record.

**Comment by harryh** [comment]
Oh nifty. Added.

**Comment by tambry** [comment]
Can access it over IPv6-only connection now (albeit the site itself doesn't work, as Twitter is IPv4-only). Thanks!
